"""HTTP views: CSV / Excel downloads and a JSON data endpoint.

Views are registered once per Home Assistant run and resolve the tracker at
request time, so they keep working after the integration is reloaded.
Downloads are meant to be opened through a *signed path* generated by the
frontend (``auth/sign_path``), which is how Home Assistant itself serves file
downloads to browsers and to the companion apps.
"""

from __future__ import annotations

from datetime import datetime
import json
import logging
from typing import Any

from aiohttp import web
from homeassistant.components.http import KEY_HASS, HomeAssistantView
from homeassistant.core import HomeAssistant, callback
from homeassistant.util import dt as dt_util

from .const import (
    CSV_DELIMITERS,
    DOMAIN,
    HTTP_DATA_PATH,
    HTTP_DOWNLOAD_CSV_FILTERED,
    HTTP_DOWNLOAD_EXCEL,
    HTTP_DOWNLOAD_PATH,
    MAX_HISTORY_RESULTS,
)
from .export import (
    ExcelExportUnavailableError,
    export_to_csv,
    export_to_excel,
    filter_history,
    get_date_range_info,
)
from .stats import summary_as_dict, zone_summary
from .tracker import PresenceTracker, async_get_tracker
from .util import parse_duration_seconds, parse_timestamp, parse_user_datetime

_LOGGER = logging.getLogger(__name__)

EXCEL_MIME = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"


class _InvalidQuery(Exception):
    """Raised when a query parameter cannot be parsed."""


def _json_error(status: int, message: str) -> web.Response:
    return web.json_response({"error": message}, status=status)


def _parse_query(query: Any) -> tuple[datetime | None, datetime | None, list[str] | None, str]:
    """Parse the common filter parameters of the download endpoints."""
    start_raw = query.get("start_date") or query.get("start")
    end_raw = query.get("end_date") or query.get("end")
    start = parse_user_datetime(start_raw)
    end = parse_user_datetime(end_raw, end_of_day=True)
    if (start_raw and start is None) or (end_raw and end is None):
        raise _InvalidQuery("Date invalide (format attendu : AAAA-MM-JJ ou ISO 8601)")
    if start and end and end < start:
        raise _InvalidQuery("La date de fin est antérieure à la date de début")
    persons_raw = query.get("persons", "")
    persons = [p.strip() for p in persons_raw.split(",") if p.strip()] or None
    delimiter = query.get("delimiter", ",")
    if delimiter not in CSV_DELIMITERS:
        raise _InvalidQuery("Séparateur CSV invalide (',' ou ';')")
    return start, end, persons, delimiter


def _stamp() -> str:
    return dt_util.now().strftime("%Y%m%d_%H%M%S")


def _attachment(filename: str) -> dict[str, str]:
    return {"Content-Disposition": f'attachment; filename="{filename}"'}


def serialise_record(record: dict[str, Any]) -> dict[str, Any]:
    """Return a record enriched with machine friendly fields for the frontend."""
    ts = parse_timestamp(record.get("timestamp"))
    seconds = parse_duration_seconds(record)
    return {
        **record,
        "timestamp_utc": ts.isoformat() if ts else None,
        "duration_seconds": None if seconds is None else round(seconds),
    }


def build_history_payload(
    tracker: PresenceTracker,
    *,
    start: datetime | None,
    end: datetime | None,
    persons: list[str] | None,
    limit: int = MAX_HISTORY_RESULTS,
) -> dict[str, Any]:
    """Filtered records (newest first) and the per-zone summary for a period."""
    now = dt_util.utcnow()
    filtered = filter_history(tracker.history, start, end, persons)
    newest_first = list(reversed(filtered))
    summary = zone_summary(
        tracker.history,
        tracker.current_states,
        start=start,
        end=end,
        persons=set(persons) if persons else None,
        now=now,
    )
    return {
        "start": start.isoformat() if start else None,
        "end": end.isoformat() if end else None,
        "total": len(filtered),
        "truncated": len(filtered) > limit,
        "records": [serialise_record(r) for r in newest_first[:limit]],
        "summary": summary_as_dict(summary),
    }


class _BaseView(HomeAssistantView):
    requires_auth = True

    @staticmethod
    def _tracker(request: web.Request) -> PresenceTracker | None:
        hass: HomeAssistant = request.app[KEY_HASS]
        return async_get_tracker(hass)


class DownloadCSVView(_BaseView):
    """Full CSV download (all data, optional delimiter)."""

    url = HTTP_DOWNLOAD_PATH
    name = "api:suivi_presence:download"

    async def get(self, request: web.Request) -> web.Response:
        tracker = self._tracker(request)
        if tracker is None:
            return _json_error(503, "Intégration non chargée")
        delimiter = request.query.get("delimiter", ",")
        if delimiter not in CSV_DELIMITERS:
            return _json_error(400, "Séparateur CSV invalide (',' ou ';')")
        content = export_to_csv(tracker.history, delimiter=delimiter, bom=True)
        return web.Response(
            body=content.encode("utf-8"),
            content_type="text/csv",
            charset="utf-8",
            headers=_attachment(f"suivi_presence_complet_{_stamp()}.csv"),
        )


class DownloadCSVFilteredView(_BaseView):
    """Filtered CSV download."""

    url = HTTP_DOWNLOAD_CSV_FILTERED
    name = "api:suivi_presence:download_csv"

    async def get(self, request: web.Request) -> web.Response:
        tracker = self._tracker(request)
        if tracker is None:
            return _json_error(503, "Intégration non chargée")
        try:
            start, end, persons, delimiter = _parse_query(request.query)
        except _InvalidQuery as err:
            return _json_error(400, str(err))
        content = export_to_csv(tracker.history, start, end, persons, delimiter=delimiter, bom=True)
        return web.Response(
            body=content.encode("utf-8"),
            content_type="text/csv",
            charset="utf-8",
            headers=_attachment(f"suivi_presence_export_{_stamp()}.csv"),
        )


class DownloadExcelView(_BaseView):
    """Excel workbook download (summary + one sheet per person)."""

    url = HTTP_DOWNLOAD_EXCEL
    name = "api:suivi_presence:download_excel"

    async def get(self, request: web.Request) -> web.Response:
        tracker = self._tracker(request)
        if tracker is None:
            return _json_error(503, "Intégration non chargée")
        try:
            start, end, persons, _ = _parse_query(request.query)
        except _InvalidQuery as err:
            return _json_error(400, str(err))
        hass: HomeAssistant = request.app[KEY_HASS]
        try:
            content = await hass.async_add_executor_job(
                lambda: export_to_excel(
                    tracker.history, tracker.current_states, start=start, end=end, persons=persons
                )
            )
        except ExcelExportUnavailableError as err:
            return _json_error(503, str(err))
        except Exception:  # noqa: BLE001 - never leak a traceback to the browser
            _LOGGER.exception("Erreur lors de la génération du fichier Excel")
            return _json_error(500, "Erreur lors de la génération du fichier Excel (voir les logs)")
        return web.Response(
            body=content,
            content_type=EXCEL_MIME,
            headers=_attachment(f"suivi_presence_rapport_{_stamp()}.xlsx"),
        )


class DashboardDataView(_BaseView):
    """JSON data for external dashboards / scripts (the card uses websocket)."""

    url = HTTP_DATA_PATH
    name = "api:suivi_presence:data"

    async def get(self, request: web.Request) -> web.Response:
        tracker = self._tracker(request)
        if tracker is None:
            return _json_error(503, "Intégration non chargée")
        try:
            start, end, persons, _ = _parse_query(request.query)
        except _InvalidQuery as err:
            return _json_error(400, str(err))
        hass: HomeAssistant = request.app[KEY_HASS]
        limit_raw = request.query.get("limit", "200")
        try:
            limit = max(1, min(int(limit_raw), MAX_HISTORY_RESULTS))
        except ValueError:
            return _json_error(400, "Paramètre limit invalide")
        payload = {
            **tracker.overview(),
            "excel_available": hass.data.get(DOMAIN, {}).get("excel_available", False),
            "data_range": get_date_range_info(tracker.history),
            "history": build_history_payload(
                tracker, start=start, end=end, persons=persons, limit=limit
            ),
            "download_urls": {
                "csv_full": HTTP_DOWNLOAD_PATH,
                "csv_filtered": HTTP_DOWNLOAD_CSV_FILTERED,
                "excel": HTTP_DOWNLOAD_EXCEL,
            },
        }
        return web.Response(
            text=json.dumps(payload, ensure_ascii=False, default=str),
            content_type="application/json",
            charset="utf-8",
        )


@callback
def async_register_views(hass: HomeAssistant) -> None:
    """Register the HTTP views (once)."""
    hass.http.register_view(DownloadCSVView())
    hass.http.register_view(DownloadCSVFilteredView())
    hass.http.register_view(DownloadExcelView())
    hass.http.register_view(DashboardDataView())
